app:
  loadUser: false
  order:
    count: 20000
  
debug: false

server:
  port: 8222

spring:
  datasource: 
    url: jdbc:h2:mem:orders_db
    username: sa
    password: welcome
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create   
    properties:
      hibernate:
        format_sql: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
                  